version: "3.8"

services:
    app:
        image: node:16-alpine
        command: sh -c "npm install && npm run start"
        ports:
            - 3000:3000
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: recipes
    
    mysql:
        image: mysql:latest
        volumes:
            - munchy-sql-data:/var/lib/mysql
            - ./src/sql:/docker-entrypoint-initdb.d
        environment:  
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: recipes
        
volumes:
  munchy-sql-data: